main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Class
    url: /class/
    weight: 3
  - name: Show
    url: /show/
    weight: 4
  - name: Work
    url: /work/
    weight: 4
  - name: Reference
    url: /reference/
    weight: 5
