main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Class
    url: /class/
    weight: 3
  - name: Show
    url: /show/
    weight: 4
  - name: Work
    url: /work/
    weight: 4
  - name: Reference
    url: /reference/
    weight: 5
  - name: '<i class="fab fa-slack"></i>'
    url: "https://soc179fs.slack.com"
    weight: 6
    

class:
  - name: Overview
    weight: 1
  - name: Content
    weight: 2
show:
  - name: Overview
    weight: 1
  - name: Examples
    weight: 2
work:
  - name: Overview
    weight: 1
  - name: Work
    weight: 2


