main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Class
    url: /class/
    weight: 3
  - name: Reference
    url: /reference/
    weight: 4
