theme = "coffee"
day_night = false
font = "sourcesans"
font_size = "M"
site_type = "Course"
description = "Visualizing Society"
logo = ""
highlight = true
highlight_languages = [
  "r"
]
highlight_style = "solarized-light"

math = true
diagram = false
privacy_pack = false
author = "Kieran Healy"
sharing_image = "soc179fs_icon.png"
twitter = "kjhealy"
date_format = "January 2, 2006"
time_format = "3:04 PM"
gravatar = false
reading_time = false
section_pager = false
docs_section_pager = false
sharing = false
link_authors = false
plugins_js = []

[edit_page]
repo_url = "https://github.com/kjhealy/visualizingsociety.com"
content_dir = ""
repo_branch = "master"

  [edit_page.editable]
  docs = false
  page = false
  post = false

[instructor]
name = "Kieran Healy"
email = "kieran.healy@duke.edu"
url = "https://kieranhealy.org"
twitter = "kjhealy"
github = "kjhealy"
office = "255 Sociology/Psychology"
contact_policy = "If you have questions or want to discuss things that we're doing in class, it's best to use the course Slack. I strongly encourage you not to be shy about raising queries or asking for help in the &#35;general channel. For other matters (such as absences, etc), email me."

[course]
number = "SOCIOL 179FS"
semester = "Fall 2020"
days = "Wed/Fri"
time = "03:30pm to 04:45pm"
location = "Soc-Psych 126"
dates = "Aug 19th - Nov 17th"
github = "kjhealy/visualizingsociety.com"
slack = "https://https://soc179fs.slack.com"
copyrightYear = "2020"

[university]
name = "Duke University"
url = "https://www.duke.edu"

[school]
name = "Sociology Department"
url = "https://sociology.duke.edu/"

[main_menu]
align = "r"
show_logo = true

[comments]
engine = 0.0

  [comments.commentable]
  page = true
  post = true
  docs = true
  project = true
  publication = true
  talk = true

  [comments.disqus]
  shortname = ""
  show_count = true

  [comments.commento]
  url = ""

[search]
engine = 0.0

  [search.algolia]
  app_id = ""
  api_key = ""
  index_name = ""
  show_logo = false

[marketing]
google_analytics = ""
google_tag_manager = ""