baseURL: "https://visualizingsociety.com/"
languageCode: en-us
title: Visualizing Society
theme: "hugo-academic"
  
# ------------------
# Building options
# ------------------
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: True

# No taxonomy
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart


copyright: ''
enableGitInfo: true
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
paginate: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>

  
# ----------------
# Output options
# ----------------
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
    
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$


    
